### ISSUE TITLE
exit code

### ISSUE THREAD

**Issue by elhaddadyacine** [Gbury/archsat#1]
Hi,
I wonder why `archsat` has the same exit code when it succeeds/fails to find a proof?

**Comment by Gbury** [comment]
Basically, the main reason is that error codes are used to specify some unexpected behavior that occurred during a run of the prover. Since it actually is a reasonably normal occurrence for a first-order prover to not find a proof and/or hit its timeout, these are treated as normal runs, hence a return code of `0`. If I remember correctly, archsat exits with exit code `1` if some unexpected error occurred during proving (i.e. some internal invariant was broken or some uncaught exception was raised), and with `2` if an error happened during startup (when reading command-line options and setting up the global state).

To distinguish between when a proof is found and when no proof is found, the best way is to grep the output of archsat. About that, note that archsat has two output modes (controlled using the `-o <mode>` option): its native mode which should be fairly human-readable, and the SZS mode, where archsat has an output which meets the [SZS ontology](http://www.tptp.org/TPTP/TPTPTParty/2007/PositionStatements/GeoffSutcliffe_SZS.html). The SZS ontology might be easier to process with a script.
